services:
  webapp:
    image: myportfolio-webapp-prod
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - production.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=MyPortfolioDb;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    env_file:
      - production.env
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DB_PASSWORD}
      MSSQL_PID: Express
    volumes:
      - sql-data-prod:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${DB_PASSWORD}' -C -Q 'SELECT 1' || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webapp
    restart: always

volumes:
  sql-data-prod: 